config/routes.rb
Rails.application.routes.draw do

  

  resources :rayons

  resources :item2s
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item2.rb
class Item2 < ApplicationRecord
  belongs_to :rayon
end

app/models/rayon.rb
class Rayon < ApplicationRecord
    has_many :item2s
    accepts_nested_attributes_for :item2s, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item2s_controller.rb
class Item2sController < ApplicationController
  before_action :set_item2, only: [:show, :edit, :update, :destroy]

  # GET /item2s
  # GET /item2s.json
  def index
    @item2s = Item2.all
    @rayons = Rayon.all
  end

  # GET /item2s/1
  # GET /item2s/1.json
  def show
    @les_rayons = Rayon.all
  end

  # GET /item2s/new
  def new
    @item2 = Item2.new
    @les_rayons = Rayon.all
  end

  # GET /item2s/1/edit
  def edit
    @les_rayons = Rayon.all
  end

  # POST /item2s
  # POST /item2s.json
  def create
    @les_rayons = Rayon.all
    @item2 = Item2.new(item2_params)

    respond_to do |format|
      if @item2.save
        format.html { redirect_to @item2, notice: 'Item2 was successfully created.' }
        format.json { render :show, status: :created, location: @item2 }
      else
        format.html { render :new }
        format.json { render json: @item2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item2s/1
  # PATCH/PUT /item2s/1.json
  def update
    respond_to do |format|
      if @item2.update(item2_params)
        format.html { redirect_to @item2, notice: 'Item2 was successfully updated.' }
        format.json { render :show, status: :ok, location: @item2 }
      else
        format.html { render :edit }
        format.json { render json: @item2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item2s/1
  # DELETE /item2s/1.json
  def destroy
    @item2.destroy
    respond_to do |format|
      format.html { redirect_to item2s_url, notice: 'Item2 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item2
      @item2 = Item2.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item2_params
      params.require(:item2).permit(:libelle, :quantite, :deja_achete, :rayon_id)
    end
end

app/controllers/rayons_controller.rb
class RayonsController < ApplicationController
  before_action :set_rayon, only: [:show, :edit, :update, :destroy]

  # GET /rayons
  # GET /rayons.json
  def index
    @rayons = Rayon.all
  end

  # GET /rayons/1
  # GET /rayons/1.json
  def show
    @les_item2s = Item2.all
    @le_rayon = Rayon.find(params[:id])
  end

  # GET /rayons/new
  def new
    @rayon = Rayon.new(libelle: params[:libelle])
    @rayon.item2s.new
  end

  # GET /rayons/1/edit
  def edit
    @rayon.item2s.new
  end

  # POST /rayons
  # POST /rayons.json
  def create
    @rayon = Rayon.new(rayon_params)

    respond_to do |format|
      if @rayon.save
        format.html { redirect_to @rayon, notice: 'Rayon was successfully created.' }
        format.json { render :show, status: :created, location: @rayon }
      else
        format.html { render :new }
        format.json { render json: @rayon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rayons/1
  # PATCH/PUT /rayons/1.json
  def update
    respond_to do |format|
      if @rayon.update(rayon_params)
        format.html { redirect_to edit_rayon_path(@rayon), notice: 'Rayon was successfully updated.' }
        format.json { render :show, status: :ok, location: @rayon }
      else
        format.html { render :edit }
        format.json { render json: @rayon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rayons/1
  # DELETE /rayons/1.json
  def destroy
    @rayon.destroy
    respond_to do |format|
      format.html { redirect_to rayons_url, notice: 'Rayon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rayon
      @rayon = Rayon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rayon_params
      params.require(:rayon).permit(:libelle, item2s_attributes:[:id, :libelle, :quantite, :deja_achete, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item2s_helper.rb
module Item2sHelper
end

app/helpers/rayons_helper.rb
module RayonsHelper
end

app/views/item2s/_form.html.erb
<%= form_with(model: item2, local: true) do |form| %>
  <% if item2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item2.errors.count, "error") %> prohibited this item2 from being saved:</h2>

      <ul>
        <% item2.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :libelle %>
    <%= form.text_field :libelle %>
  </div>

  <div class="field">
    <%= form.label :quantite %>
    <%= form.number_field :quantite %>
  </div>

  <div class="field">
    <%= form.label :deja_achete %>
    <%= form.check_box :deja_achete %>
  </div>

  <div class="field">
  <label id="rayon_id">Nom du rayon: </label>
  <select name="rayon_id">
    <% @les_rayons.each do |rayon| %>
      <option value="<%= rayon.id %>"><%= rayon.libelle %></option>
    <% end %>
  </select>
</div>

</br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/item2s/edit.html.erb
<h1>Modification d'un produit</h1>
</br>

<%= render 'form', item2: @item2 %>

</br>
<%= link_to 'informations', @item2 %> |
<%= link_to 'Retour', item2s_path %>

app/views/item2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>On fait les courses</h1>

<% @rayons.each do |rayon| %>
  </br><strong><%= rayon.libelle %></strong></br></br>
  <% @item2s.each do |item2| %>
    <% if item2.rayon_id == rayon.id %>
      <%= item2.libelle %> (<%= item2.quantite %>)
      <%= link_to '[Infos]', item2 %>
      <%= link_to '[M]', edit_item2_path(item2) %>
      <%= link_to '[S]', item2, method: :delete, data: { confirm: 'Are you sure?' } %></br>
    <% end %>  
  <% end %>
<% end %>

<br>
<%= link_to 'Ajouter un produit', new_item2_path %>
</br>
<a href="/rayons">Liste des rayons</a>

</br></br>

app/views/item2s/new.html.erb
<h1>Ajout d'un produit</h1>
</br>

<%= render 'form', item2: @item2 %>

</br>
<%= link_to 'retour', item2s_path %>

app/views/item2s/show.html.erb
<p id="notice"><%= notice %></p>

<% @les_rayons.each do |le_rayon| %>
  <% if le_rayon.id == @item2.rayon_id %>
    <h1><%= le_rayon.libelle %></h1>
  <% end %>
<% end %>
</br>
<p>
  <strong>Nom :</strong>
  <%= @item2.libelle %>
</p>

<p>
  <strong>Quantite :</strong>
  <%= @item2.quantite %>
</p>

<p>
  <strong>Deja achete :</strong>
  <% if @item2.deja_achete == false %>
    ✘
  <% else %>
    ✔
  <% end %>
</p>

</br>
<%= link_to 'Modifier', edit_item2_path(@item2) %> |
<%= link_to 'Retour', item2s_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListeCourse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rayons/_form.html.erb
<%= form_with(model: rayon, local: true) do |form| %>
  <% if rayon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rayon.errors.count, "error") %> prohibited this rayon from being saved:</h2>

      <ul>
        <% rayon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form_for @rayon do |rayon_form| %>
      <label for='rayon_item2s_attributes_0_libelle'>
        Rayon:
      </label>

      <%= rayon_form.text_field :libelle %>
    
      <fieldset>
        <legend>Produits</legend>

        <%= rayon_form.fields_for :item2s do |item2| %>
          <div>
            Nom: <%= item2.text_field :libelle, autofocus: item2.object.libelle.nil? %>
            Quantité: <%= item2.number_field :quantite %>
            Deja acheté: <%= item2.check_box :deja_achete, {}, true, false %>

            Supprimer: <%= item2.check_box :_destroy %>
          </div>
        <% end %>
      </fieldset>
    <% end %>
    </form>
  
  </br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rayons/edit.html.erb
<h1>Modification d'un rayon</h1>
</br>

<%= render 'form', rayon: @rayon %>

</br>
<%= link_to 'Informations', @rayon %> |
<%= link_to 'Retour', rayons_path %>

app/views/rayons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des rayons</h1>

<table>
  <thead>
    <tr>
      <th>Nom :</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  </br>

  <tbody>
    <% @rayons.each do |rayon| %>
      <tr>
        <td><%= rayon.libelle %></td>
        <td><%= link_to 'Informations', rayon %></td>
        <td><%= link_to 'Modifier', edit_rayon_path(rayon) %></td>
        <td><%= link_to 'Supprimer', rayon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 
<%= link_to 'Ajouter un rayon', new_rayon_path %> |
<%= link_to 'Retour', item2s_path %>

app/views/rayons/new.html.erb
<h1>Ajout d'un rayon</h1>

<%= render 'form', rayon: @rayon %>

<%= link_to 'Retour', rayons_path %>

app/views/rayons/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @rayon.libelle %></h1>
</br>
<p>
  <strong>Nom :</strong>
  <%= @rayon.libelle %>
</p>

<% @les_item2s.each do |le_item2| %>
  <% if le_item2.rayon_id == @le_rayon.id %>
    <p><%= le_item2.libelle %></p>
  <% end %>
<% end %>

</br>
<%= link_to 'Modifier', edit_rayon_path(@rayon) %> |
<%= link_to 'Retour', rayons_path %>